name: CMake

on:
  push:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Download Boost
      shell: powershell
      run: |
        $uri = 'https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.zip'
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $uri -OutFile C:\boost.zip -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
        
    - name: Unzip boost
      run: Expand-Archive -LiteralPath 'C:\boost.zip' -DestinationPath C:\install\
      
    - name: Run bootstrap
      shell: powershell
      run: |
        cd C:\install\boost_1_68_0\tools\build\
        .\bootstrap.bat gcc
        
    - name: Install Boost
      continue-on-error: true
      shell: powershell
      run: |
        cd C:\install\boost_1_68_0\tools\build\
        .\b2 --with-system --with-filesystem --with-thread --with-date_time --with-test --build-type=complete -j2 --prefix="C:\boost-build" toolset=gcc install
        $env:Path += ";C:\boost-build\bin"
        cd C:\install\boost_1_68_0
        C:\boost-build\bin\b2.exe --with-system --with-filesystem --with-thread --with-date_time --with-test --build-type=complete -j2 --build-dir="C:\install\boost_1_68_0\build" --build-type=complete --prefix="C:\boost" toolset=gcc install

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        $env:BOOST_INCLUDEDIR = 'C:\boost\include'
        $env:BOOST_LIBRARYDIR = 'C:\boost\lib'
        $env:BOOST_ROOT = 'C:\boost'
        cmake -DBOOST_ROOT=C:\boost -DBOOST_INCLUDEDIR=C:\boost\lib -DBOOST_LIBRARYDIR=C:\boost\include -DBoost_ARCHITECTURE="-x64" -DBoost_DEBUG=ON -G "MinGW Makefiles" --build .. --config $BUILD_TYPE

    - name: Running make (MinGW)
      working-directory: ${{runner.workspace}}/build
      run: make
